# Generated by Django 6.0.1 on 2026-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='comments/')),
            ],
        ),
    ]
