# Generated by Django 6.0.1 on 2026-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_restore_single_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
