# Generated by Django 5.2.10 on 2026-02-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_faq_rename_type_project_category_project_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='your_services',
            field=models.CharField(blank=True, null=True),
        ),
    ]
