# Generated by Django 5.2.10 on 2026-01-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_projectimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255)),
                ('question_ar', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255)),
                ('answer_uz', models.CharField(max_length=255)),
                ('answer_en', models.CharField(max_length=255)),
                ('answer_ar', models.CharField(max_length=255)),
                ('answer_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='app.service'),
        ),
    ]
